import type { Metadata, Viewport } from "next";
import "./globals.css";
import "react-calendar/dist/Calendar.css";
import { Header } from "@/components/Header";
import { pretendard } from "./fonts/pretendard";
import { Modal } from "@/components/Modal";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "MapleDot: 메닷",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${pretendard.variable} font-pretendard bg-white dark:bg-[#131313] min-h-screen flex flex-col`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Header />
          <Modal />
          <main className="flex-1">{children}</main>
          <footer className="flex justify-center items-center py-4 border-t border-slate-200 dark:border-white/10">
            <p className="text-sm text-slate-600 dark:text-slate-400">
              © 2025 MapleDot. All rights reserved. | Data based on <span className="font-bold">NEXON Open API</span>
            </p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
