import type { Metadata } from "next";
import "./globals.css";
import "react-calendar/dist/Calendar.css";
import { Header } from "@/components/Header";
import { SideBar } from "@/components/SideBar";
import { NoticeSideBar } from "@/components/NoticeSideBar";
import { pretendard } from "./fonts/pretendard";
import { Modal } from "@/components/Modal";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "MapleDot: 메닷",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${pretendard.variable} font-pretendard bg-white dark:bg-[#131313]`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <Header />
          <Modal />
          <div className="flex flex-row h-full gap-4">
            <SideBar />
            {children}
            <NoticeSideBar />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
