type MainStat = "str" | "dex" | "int" | "luk" | "hp" | "str+dex+luk";
type MainPower = "공격력" | "마력";
type JobStat = {
  mainStat: MainStat;
  mainPower: MainPower;
};

export const JOB_STAT: Record<string, JobStat> = {
  히어로: { mainStat: "str", mainPower: "공격력" },
  팔라딘: { mainStat: "str", mainPower: "공격력" },
  다크나이트: { mainStat: "str", mainPower: "공격력" },
  소울마스터: { mainStat: "str", mainPower: "공격력" },
  미하일: { mainStat: "str", mainPower: "공격력" },
  블래스터: { mainStat: "str", mainPower: "공격력" },
  "데몬 슬레이어": { mainStat: "str", mainPower: "공격력" },
  아란: { mainStat: "str", mainPower: "공격력" },
  카이저: { mainStat: "str", mainPower: "공격력" },
  아델: { mainStat: "str", mainPower: "공격력" },
  제로: { mainStat: "str", mainPower: "공격력" },
  바이퍼: { mainStat: "str", mainPower: "공격력" },
  캐논마스터: { mainStat: "str", mainPower: "공격력" },
  스트라이커: { mainStat: "str", mainPower: "공격력" },
  은월: { mainStat: "str", mainPower: "공격력" },
  아크: { mainStat: "str", mainPower: "공격력" },
  제논: { mainStat: "str+dex+luk", mainPower: "공격력" },
  렌: { mainStat: "str", mainPower: "공격력" },
  보우마스터: { mainStat: "dex", mainPower: "공격력" },
  신궁: { mainStat: "dex", mainPower: "공격력" },
  메카닉: { mainStat: "dex", mainPower: "공격력" },
  패스파인더: { mainStat: "dex", mainPower: "공격력" },
  윈드브레이커: { mainStat: "dex", mainPower: "공격력" },
  와일드헌터: { mainStat: "dex", mainPower: "공격력" },
  카인: { mainStat: "dex", mainPower: "공격력" },
  메르세데스: { mainStat: "dex", mainPower: "공격력" },
  캡틴: { mainStat: "dex", mainPower: "공격력" },
  엔젤릭버스터: { mainStat: "dex", mainPower: "공격력" },
  "아크메이지(불,독)": { mainStat: "int", mainPower: "마력" },
  "아크메이지(썬,콜)": { mainStat: "int", mainPower: "마력" },
  비숍: { mainStat: "int", mainPower: "마력" },
  플레임위자드: { mainStat: "int", mainPower: "마력" },
  배틀메이지: { mainStat: "int", mainPower: "마력" },
  루미너스: { mainStat: "int", mainPower: "마력" },
  에반: { mainStat: "int", mainPower: "마력" },
  일리움: { mainStat: "int", mainPower: "마력" },
  라라: { mainStat: "int", mainPower: "마력" },
  키네시스: { mainStat: "int", mainPower: "마력" },
  나이트로드: { mainStat: "luk", mainPower: "공격력" },
  섀도어: { mainStat: "luk", mainPower: "공격력" },
  듀얼블레이더: { mainStat: "luk", mainPower: "공격력" },
  나이트워커: { mainStat: "luk", mainPower: "공격력" },
  팬텀: { mainStat: "luk", mainPower: "공격력" },
  카데나: { mainStat: "luk", mainPower: "공격력" },
  칼리: { mainStat: "luk", mainPower: "공격력" },
  호영: { mainStat: "luk", mainPower: "공격력" },
  데몬어벤져: { mainStat: "hp", mainPower: "공격력" },
} as const;
